### ISSUE TITLE
Remove dependency on std::auto_ptr in unit tests

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/libuavcan#100]
`std::auto_ptr<>` has been removed from newer versions of  STL.

It should be noted that its replacement to newer means of automatic memory management will break the C++03 unit tests. Perhaps the affected tests should be disabled for the C++03 mode. The resulting lack of coverage should be tolerable, especially considering my intention to drop the support for C++03 at some point in the future.

**Comment by thirtytwobits** [comment]
I'd very much like to drop C++03 support. It adds considerable complexity to the codebase and build time to the unittests. Requiring C++11 shouldn't be controversial at all. This has almost universal support at this point.
