### ISSUE TITLE
Add explicit support for C++14 and newer

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/libuavcan#101]
Currently the library cannot be compiled with C++14 and newer unless `UAVCAN_CPP_VERSION` is overridden.

**Comment by antoinealb** [comment]
Bumping this as we are facing this issue when trying to build our project using C++14. Is there anything blocking support for C++14 or is it just a matter of adding correct detection logic to `build_config.hpp`?

**Comment by pavel-kirienko** [comment]
Yes the change would be very trivial as you described. Or you could just define `UAVCAN_CPP_VERSION=UAVCAN_CPP11`.

**Comment by thirtytwobits** [comment]
I think we need to fix up the top level CMakeLists.txt. I'll post a PR to see what we think of my plan.

**Comment by thirtytwobits** [comment]
Closing as we allow it now. Issue #228 tracks remaining issues.
