### ISSUE TITLE
UAVCAN in JAVA?

### ISSUE THREAD

**Issue by karu2003** [UAVCAN/libuavcan#103]
Hello All.
There are implementations of UAVCAN in JAVA?

Thank you.
Andrew.

**Comment by pavel-kirienko** [comment]
No, but you're welcome to propose one!

Meanwhile you may find PyUAVCAN helpful.

Please submit further questions either to the [mailing list](https://groups.google.com/forum/#!forum/uavcan) or to the [chat room](https://gitter.im/UAVCAN/general). This issue tracker is for issues only. Thanks!
