### ISSUE TITLE
How to cross compile libuavcan on stm32?

### ISSUE THREAD

**Issue by mymbrooks** [UAVCAN/libuavcan#120]
I'm new on arm embedded develop.I want to cross compile libuavcan on stm32.
I have installed all dependencies: python cmake arm-none-eabi-gcc ...
I followed readme and doc but failed.

mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-stm32-cortex-m4.cmake
make -j8

Where is Toolchain-stm32-cortex-m4.cmake? How to write this cmake file?
Thanks.

--------------------------------------------------------------------------------------------------------
Remark1:
I have compile on x86. cross compile is still failed.

**Comment by pavel-kirienko** [comment]
Just pushed an update to README.md which should make things clearer.

tl;dr CMake is not for your use case; use Make instead.

**Comment by Cherish-Gww** [comment]
Is there have a example for Toolchain-stm32-cortex-m4.cmake?

**Comment by pavel-kirienko** [comment]
Eh, don't go there, use make.
