### ISSUE TITLE
why Multiple repeated calls to the sending function ，then%cpu : 90%+ 

### ISSUE THREAD

**Issue by programdog** [UAVCAN/libuavcan#126]
in px4 , like rgbled  . i  make  a moudle : uavcan_rgbled ,
I use : work_queue(LPWORK, &_work, (worker_t)&UavcanRgbled::led_trampoline, this, _led_interval/8);

-----------------------------------------------------------------------------------------------
this Call flow : (When it's time to call again and again)
led_trampoline() 
                         ->led()->send_led_rgb()
                                                             ->_rgbled_pub.broadcast(msg)
------------------------------------------------------------------------------------------------

but Random time （1~5min）：look at the CPU  90%+!!
 PID     USER     PR  NI    VIRT    RES    SHR S    %CPU    %MEM     TIME+
123117 root      20   0  170276  39112   4660 S    94.4       1.9   0:10.33

Why did this happen?  thank you for your help

**Comment by pavel-kirienko** [comment]
Let's have a look at the code.

**Comment by programdog** [comment]
I compressed 4 file ：uavcan_main.cpp , uavcan_main.hpp , rgbled.cpp , rgbled. hpp 

in **uavcan_main.cpp** in line 665 only use command of "rgbled" to  get into “rgbled_test()” then use RGBLED_MODE_BLINK_FAST ，then get into rgbled.cpp to handle。

in rgbled.cpp ，Function jump like ：

 uavcan_rgbled_set_mode(RGBLED_MODE_BLINK_FAST) -》set_mode(); -》 work_queue(); -》led_trampoline() -》led()-》work_queue() 

then When it's time to call again and again when i use function Flicker 

but Random time （1~5min）：look at the CPU 90%+!!
PID USER PR NI VIRT RES SHR S **%CPU** %MEM TIME+
123117 root 20 0 170276 39112 4660 S **94.4** 1.9 0:10.33

Why did this happen? thank you for your help

[uavcan_rgbled.zip](https://github.com/UAVCAN/libuavcan/files/1969405/uavcan_rgbled.zip)

**Comment by programdog** [comment]
-_-!

**Comment by programdog** [comment]
[~_~ ]

**Comment by programdog** [comment]
~_~#

**Comment by programdog** [comment]
=_=*

**Comment by pavel-kirienko** [comment]
You don't initialize the field `_pattern.duration`. It remains at zero after the memset call in the constructor, leading to continuous requeuing of your handler.

Please note that this is not an appropriate place for general programming questions.

**Comment by programdog** [comment]
thankyou for your help , I'll try again。It may not be a code problem ，I will keep finding，then I will tell you what i am finding.
