### ISSUE TITLE
googletest is not an explicit dependency

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/libuavcan#132]
Googletest/googlemock shouldn't come from the environment but should come in as a submodule or other mechanism. The docs for CMAKE/gtest integration (https://github.com/google/googletest/blob/master/googletest/README.md) recommend pulling the dependency from github (I'll submit a patch that uses this method).

**Comment by pavel-kirienko** [comment]
We should abandon GTest and migrate to Catch2 instead, I think

**Comment by thirtytwobits** [comment]
I don't believe catch2 supports mocks. You get gmock for free when you use googletest. Libuavcan would do well to use gmock more. I also submitted a patch to make this less painful.

**Comment by pavel-kirienko** [comment]
I guess now it is a dependency.
