### ISSUE TITLE
Add a .clang-format that enforces Zubax coding conventions

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/libuavcan#144]
.clang-format should enforce as much of https://kb.zubax.com/pages/viewpage.action?pageId=2195699 as is supported by that technology.

Protip: Use a tool like https://clangformat.com/ to help.

**Comment by antoinealb** [comment]
There is already an uncrustify config for the Zubax style guide apparently: https://kb.zubax.com/pages/viewpage.action?pageId=2195703

**Comment by pavel-kirienko** [comment]
Uncrustify sucks. I heard people say that clang-format sucks considerably less, but I had no chance to verify that myself yet.

**Comment by SyrianSpock** [comment]
Using clang-format (6.0) for the last few months at work (C++ code base), and it works way better than uncrustify in my experience. The config file is also much easier to setup.

**Comment by thirtytwobits** [comment]
Yeah, clang-format is emerging as a defacto standard for code formatting. It's supported everywhere now
