### ISSUE TITLE
depricated ifconfig

### ISSUE THREAD

**Issue by hjoertel** [UAVCAN/libuavcan#154]
Some Linux distributions have deprecated the use of ifconfig and route in favor of the software suite iproute2.
ifconfig is used in 
libuavcan/libuavcan_drivers/linux/scripts/uavcan_add_vcan
The icfonfig should be replaced bei ip

**Comment by hjoertel** [comment]
I'll try. Already fixed the script. I'm not very familiar with git, still mostly use svn :-)

**Comment by pavel-kirienko** [comment]
Fixed in https://github.com/UAVCAN/libuavcan/pull/155
