### ISSUE TITLE
Add "get adjustment" method to ISystemClock

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/libuavcan#164]
When working on improving the SystemClock abstraction in libuavcan_linux we ran into an issue where the core driver depended on an implementation-specific method, getPrivateAdjusment. To allow creation of drivers that only use ISystemClock we would like to add a generic version of this method to the ISystemClock interface.

**Comment by pavel-kirienko** [comment]
I don't like this. `getPrivateAdjustment()` is a bit of a hack, needed to work around the case where the node needs to be time-synced with the network, while not changing the system-wide clock settings. The whole concept of it is very specific to the Linux platform driver. Can you not just add a lower-level interface underneath `ISystemClock`, say, `IPrivateSystemClock`?

**Comment by thirtytwobits** [comment]
Take a look at my PR and see if it makes sense when you read the comments?

**Comment by pavel-kirienko** [comment]
```
     * Note that this value is not necessarily the value set via adjustUtc(UtcDuration) but may be 
     * related for some implementations. For example, where a system clock implements adjustUtc(UtcDuration)
     * by adjusting the actual system time this method will always return 0 since time obtained from this 
     * system no longer needs to be adjusted. The opposite is true where an implementation cannot adjust 
     * the system time and so must always manually apply this adjustment to any value retrived from
     * the system.
```

What I'm reading is that the behavior would still be implementation-defined, but the interface will be unified. Why not express it clearly by adding a dedicated interface?

**Comment by thirtytwobits** [comment]
because it's expressing how the ISystemClock::getUtc() method is determining its value. The two methods are closely related and so part of the same interface (IMHO).

**Comment by pavel-kirienko** [comment]
> because it's expressing how the ISystemClock::getUtc() method is determining its value.

But that's not quite the case. The interface does not put any constraints on the way `getUtc()` operates. I think adding this method is undesirable because it undermines encapsulation, and it can be easily abused to create implementations tightly coupled with a particular implementation of the clock driver, which is undesirable.

**Comment by thirtytwobits** [comment]
Okay. So how about ISystemClockAdjustment then?

**Comment by pavel-kirienko** [comment]
Could you please elaborate a bit on the overall objective?

> To allow creation of drivers that only use ISystemClock we would like to add a generic version of this method to the ISystemClock interface.

As I understand it, you want a SocketCAN driver that doesn't use the Linux-specific implementation of ISystemClock?

**Comment by thirtytwobits** [comment]
I'm working on a more "posix" friendly abstraction. One of the things I'm running into is that the current SystemClock implementation doesn't work on one of my target RTOS platforms. I want to be able to reuse the socketcan.hpp driver but with a different systemclock implementation. I'll submit a PR for doing this down in the libuavcan_linux layer.

**Comment by thirtytwobits** [comment]
Gah! the linux driver is all hosed when building against v1. I'll need to finish the fd port for this package. I'll create a v1 branch in this package and submit a PR later this week.

**Comment by pavel-kirienko** [comment]
Do we still want this open?

**Comment by thirtytwobits** [comment]
I guess not. Seems like the v1 changes are more fundamental then this.
