### ISSUE TITLE
DSDL compilation

### ISSUE THREAD

**Issue by SergeyF1987** [UAVCAN/libuavcan#173]
I feel so stupid.. But I cannot understand how can I do DSDL compilation.
So... I get messages like "Timestamp.hpp" - no such file or directory. So, I read about this at 
https://uavcan.org/Implementations/Libuavcan/FAQ/
"This could be caused by failing DSDL compilation - see below."
But no any usefull information below
As I understood I must launch command in pre-build string in Eclipse like:
C:\Python36\python.exe  D:\CANtest\EmptyCAN2\libuavcan\libuavcan\dsdl_compiler\libuavcan_dsdlc
But... Nothing happens..  I cannot compile and find "Timestamp.hpp" or other needed hpp-files
//------------------
Python 3.6 is correctly installed, C++11 is using.
Through CMD it says - "error: the following arguments are required: 'source_dir'"
But how fix it??

**Comment by thirtytwobits** [comment]
You have to supply the path to the DSDL files. In libuavcan's master branch this is a submodule mounted under the "dsdl" directory.

**Comment by pavel-kirienko** [comment]
Here: https://github.com/UAVCAN/libuavcan_stm32#using-make look for the text "Invoke DSDL compiler and add its default output directory to the include search path"

**Comment by pavel-kirienko** [comment]
Wrote a few sentences about libuavcan_dsdlc here: https://uavcan.org/Implementations/Libuavcan/#dsdl-compiler
