### ISSUE TITLE
libuavcan doesn't compile if UAVCAN_DEBUG, UAVCAN_TOSTRING and UAVCAN_EXCEPTIONS are not defined

### ISSUE THREAD

**Issue by DrTon** [UAVCAN/libuavcan#175]
Compiler: arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]

Problem that even if UAVCAN_DEBUG is disabled compiler tries to find toString() method, that is not defined when UAVCAN_TOSTRING is not defined, which requires UAVCAN_EXCEPTIONS, that I don't want to use. I.e. RELEASE build is not possible without exceptions.

https://github.com/UAVCAN/libuavcan/blob/67da0aae7dd4eedae7905ab98941592cebab4723/libuavcan/include/uavcan/transport/outgoing_transfer_registry.hpp#L89

```
.../libuavcan/./libuavcan/include/uavcan/transport/outgoing_transfer_registry.hpp: In member function 'bool uavcan::OutgoingTransferRegistry::DeadlineExpiredPredicate::operator()(const uavcan::OutgoingTransferRegistryKey&, const uavcan::OutgoingTransferRegistry::Value&) const':
.../libuavcan/./libuavcan/include/uavcan/transport/outgoing_transfer_registry.hpp:89:34: error: 'const class uavcan::OutgoingTransferRegistryKey' has no member named 'toString'
                              key.toString().c_str(), int(value.tid.get()));
```

UPDATE: When UAVCAN_DEBUG is enabled it doesn't compile too because of the same key.toString()

**Comment by pavel-kirienko** [comment]
> Problem that even if UAVCAN_DEBUG is disabled compiler tries to find toString() method

That can't be true. The line you're referring to is a trace statement; `UAVCAN_TRACE` is defined to expand into a no-op unless `UAVCAN_DEBUG` is enabled: https://github.com/UAVCAN/libuavcan/blob/67da0aae7dd4eedae7905ab98941592cebab4723/libuavcan/include/uavcan/debug.hpp#L31

Seeing as your compiler is looking for `toString()` nevertheless, you must be trying to build a debug build with `UAVCAN_DEBUG` enabled, which is not supposed to be used in production (it's intended mostly for testing and development). Let us have a look at your build log.

Other than that, if `UAVCAN_DEBUG` is enabled, both `UAVCAN_TOSTRING` and `UAVCAN_EXCEPTIONS` are required, but as I said, that does not affect release environments.

**Comment by DrTon** [comment]
Sorry, my mistake, UAVCAN_DEBUG was enabled in another place. Compiles now!
