### ISSUE TITLE
How configure node params?? (question, not issue)

### ISSUE THREAD

**Issue by SergeyF1987** [UAVCAN/libuavcan#177]
I fixed my troubles, that I described below, but now I have a question about one thing, that I still cannot understand completely.
 I want define some inner params for node (configure node). I read this tutorial.
https://uavcan.org/Implementations/Libuavcan/Tutorials/7._Remote_node_reconfiguration/
Did I understand right, that I must initialize and launch ParamServer (Remote node section) and then set (or read) params through uavcan::protocol::param::GetSet::Request (Response);
I need add (define) a new param in node (in node space) for reconfiguring it at next. How can do I this?

**Comment by pavel-kirienko** [comment]
The library is interfaced with your application via the `uavcan::IParamManager` interface: https://github.com/UAVCAN/libuavcan/blob/dfcdf22eda16ff06847976fd6c7f40671fc92eb5/libuavcan/include/uavcan/protocol/param_server.hpp#L22

It is entirely up to you to decide how to handle your configuration parameters, how to add a new one, how to modify them, and so on.

P.S. this space is for development and troubleshooting purposes only. If you'd like to ask a question, please, do so on the [UAVCAN Forum](http://uavcan.org).
