### ISSUE TITLE
Fail to generate dsdl with python 3.7.2

### ISSUE THREAD

**Issue by patrickelectric** [UAVCAN/libuavcan#197]
It works fine with python2.
Please see the log here:
https://github.com/ArduPilot/ardupilot/issues/10333

**Comment by thirtytwobits** [comment]
I  believe this got fixed by https://github.com/UAVCAN/libuavcan/commit/479d144ded9d5d16e234121ef9511b9ca9dfdac5 ? 

Please reopen if this is still a problem.
