### ISSUE TITLE
scalar_codec.hpp UAVCAN_ASSERT on big_endian processor

### ISSUE THREAD

**Issue by jacobschloss** [UAVCAN/libuavcan#205]
It looks like there is an assert for big endian processors based on portability concerns / lack of testing.

We are running libuavcan on a big endian processor (PowerPC e200z7, NXP MPC5777M), so will be able to provide testing. Once we confirm that it all works, can we remove [this assert](https://github.com/UAVCAN/libuavcan/blob/dfcdf22eda16ff06847976fd6c7f40671fc92eb5/libuavcan/include/uavcan/marshal/scalar_codec.hpp#L41) in convertByteOrder? We'll probably have it up and running this week.

**Comment by pavel-kirienko** [comment]
Yes, please do that, and send us a pull request, too. Thanks!
