### ISSUE TITLE
Port driver layer to uavcan v1

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/libuavcan#222]
UAVCAN v1 will not have anything named "driver" in it so we want to move things that were in v0 "driver" into either platform or transport/bus.

**Comment by pavel-kirienko** [comment]
FWIW in Pyuavcan, I've come up with the following layer structure for the network abstractions:

(application) <--> Node <--> Presentation <--> Transport <--> Media <--> (hardware)

Where "Presentation" implements the transport-agnostic communication logic (such as pub/sub, calls, DSDL serialization), and different transports implement an abstract interface `Transport`. Each transport implementation has an abstract `Media` interface specific for that transport which abstracts the implementation details for different types of backends, such as SocketCAN or SLCAN for the CAN transport, or the Berkeley sockets for the experimental UDP transport.

(redundant transports are supported through a special type of transport which aggregates several regular transports together according to the logic described in the spec)

The term "media" seems to match the usage well, so perhaps you might want to consider its use for libuavcan, too.
