### ISSUE TITLE
Build Nunavut templates for v1 types.

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/libuavcan#234]
This is a placeholder. Hopefully I can break this down in to a few tasks rather that one big uber-task.

**Comment by pavel-kirienko** [comment]
Relevant notes on near-zero-cost serialization with the help of bit length analysis available in PyDSDL v1.0: https://github.com/UAVCAN/pydsdl/pull/24

Relevant excerpts from the PyUAVCAN (de)serialization code generation:
- https://github.com/UAVCAN/pyuavcan/blob/d986161a5775af79e7367f16da0616c198838775/pyuavcan/dsdl/_templates/serialization.j2#L55-L127
- https://github.com/UAVCAN/pyuavcan/blob/d986161a5775af79e7367f16da0616c198838775/pyuavcan/dsdl/_templates/deserialization.j2#L27-L126

**Comment by thirtytwobits** [comment]
Closing as this is superseded by https://github.com/UAVCAN/nunavut/issues/91.
