### ISSUE TITLE
Infinite loop in the AVL tree

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/libuavcan#254]
It has been reported that there is allegedly an infinite loop in the AVL tree:

https://forum.uavcan.org/t/libuavcan-cubemx-freertos-systemworkbenchforstm32/430/9?u=pavel.kirienko

**Comment by dpslwk** [comment]
fix suggested by kolos450 in the linked thread got this working for me on an STM32L433 under FreeRTOS

**Comment by pavel-kirienko** [comment]
For reference, this is the suggested fix copy-pasted from the forum verbatim:

> Hi. I've got the same issue. There is a typo in the appendToEndOf method:
> ```
> target = head->equal_keys;
> ```
> should be 
> ```
> target = target->equal_keys;
> ```
> The case happens when the driver is busy and all the frames produced from a single message are sent to a linked list.

@thirtytwobits should we just go ahead and fix this, seeing as @Zarkopafilis is unavailable?

**Comment by pavel-kirienko** [comment]
Related: https://forum.uavcan.org/t/how-to-support-getnodeinfo-and-getdatatypeinfo-on-stm32/577

**Comment by thirtytwobits** [comment]
I'll take a look

**Comment by thirtytwobits** [comment]
All fixed. Thanks for the bug report and sorry for the slow response.
