### ISSUE TITLE
IRQ for STM32L4

### ISSUE THREAD

**Issue by teklike** [UAVCAN/libuavcan#256]
I am using libuavcan to send single frame broadcast messages.  On going through the debugging process, I noticed in the uc_stm32_can.cpp file,  there are defines for STM32F3XX and STM32 processors running NUTTX etc. with specific mappings for CAN interrupt Handlers.  But although there is mention of freeRTOS on STM32 .... there is no mapping. Is this truly correct or we need to add to this file similar mappings for STM32L4 running FREERTOS? (And if so.... could  I be pointed to a location, where there is an example for this?) 

My exact processor is STM32L4A6VG, running FreeRTOS.

**Comment by teklike** [comment]
running the file as is, I get the following errors:
![image](https://user-images.githubusercontent.com/19983939/61256274-ff911100-a720-11e9-89dc-e925e65de744.png)

**Comment by teklike** [comment]
[stm32l4a6xx.zip](https://github.com/UAVCAN/libuavcan/files/3394696/stm32l4a6xx.zip)
[stm32l4xx_hal_conf.zip](https://github.com/UAVCAN/libuavcan/files/3394699/stm32l4xx_hal_conf.zip)

Processor register and config Files for stm32l4a6xx

**Comment by dpslwk** [comment]
https://github.com/UAVCAN/libuavcan_stm32/pull/3

**Comment by pavel-kirienko** [comment]
My best suggestion is to abandon the stock STM32 driver we have and use your own. You can use the stock one as a starting point (MIT license); drop all preprocessor branches your platform does not require (that'll cut the code size by a third I expect) and then add the missing bits in there.

I think in v1 we might need to have a narrower focus for this driver. Maybe there should be just one implementation for baremetal and a dedicated implementation per RTOS. If you feel strongly about this, consider jumping onto our [dev call tomorrow at 18:00 UTC](https://forum.uavcan.org/t/weekly-dev-call/173].
