### ISSUE TITLE
CMake ERROR: ModuleNotFoundError: No module named 'uavcan'

### ISSUE THREAD

**Issue by jiapei100** [UAVCAN/libuavcan#258]
Is it possible to build **C/C++ ONLY, without Python** ?

```
[  1%] Running dsdl compiler
cd ....../UAVCAN/libuavcan/libuavcan && /usr/bin/python ....../UAVCAN/libuavcan/libuavcan/dsdl_compiler/libuavcan_dsdlc test/dsdl_test/root_ns_a test/dsdl_test/root_ns_b ....../UAVCAN/libuavcan/libuavcan/../dsdl/uavcan -Oinclude/dsdlc_generated
Traceback (most recent call last):
  File "....../UAVCAN/libuavcan/libuavcan/dsdl_compiler/libuavcan_dsdlc", line 59, in <module>
    from libuavcan_dsdl_compiler import run as dsdlc_run
  File "....../UAVCAN/libuavcan/libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py", line 18, in <module>
    from uavcan import dsdl
ModuleNotFoundError: No module named 'uavcan'
```

**Comment by thirtytwobits** [comment]
Unfortunately, no. The python is used to generate C++ types from DSDL. These types are part of the core protocol. We will improve this integration with UAVCAN v1 but regardless we will always require python generation from DSDL as part of the libuavcan build.

**Comment by thirtytwobits** [comment]
As for your issue, don't forget to `git submodule update --init`

**Comment by jiapei100** [comment]
@thirtytwobits You are right... Problem solved...

**Comment by deworben** [comment]
I had to run this with force to get this to work: `git submodule update --init --recursive --force`
