### ISSUE TITLE
Move all cmake machinery under tst

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/libuavcan#264]
To reduce confusion we want to move all the cmake machinery we currently have to live under the test folder. At the top level we should provide something very basic (Makefile?) and documentation to help users integrate libuavcan and nnvg with their application.

**Comment by pavel-kirienko** [comment]
> At the top level we should provide something very basic (Makefile?) and documentation to help users integrate libuavcan and nnvg with their application.

Maybe we should provide *nothing* on the top level except for documentation? I recall seeing users of IAR or Keil IDE not knowing what to do with a makefile. Examples for particular build systems could be moved somewhere into deeper chapters of the user documentation.
