### ISSUE TITLE
Consider renaming the library

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/libuavcan#276]
Libuavcan implements the UAVCAN/CAN transport only. When UAVCAN/UDP or some other transport is around, the name Libuavcan will be causing confusion. We should consider finding a better name for the library that reflects its CAN-focused nature better. A possible alternative is **libuavcancan** :dancer:.

**Comment by LorenzMeier** [comment]
Given that there are limited resources to work on UAVCAN I would make sure you're not getting ahead of yourself. At a point where the core maintenance team is already overloaded implementing the new revision for CAN adding another physical layer seems a dilution of critical resources.

There is no great standard for CAN for drones, but there are dozens of realtime pub/sub protocols to choose from on a UDP transport, so the uptake there is much harder.

**Comment by pavel-kirienko** [comment]
The cost of renaming is strongly correlated with adoption, so if we expect that it might become necessary in the future, it is rational to do it soon. It does not imply that we are already dedicating resources to other transports now.

**Comment by LorenzMeier** [comment]
Cool, that's reassuring. Thinking ahead is great!

**Comment by pavel-kirienko** [comment]
We decided to keep it as-is because we do intend to engineer the support for other transports into Libuavcan. CAN FD is obviously the number one target. Follow the details on the forum.

**Comment by thirtytwobits** [comment]
The dream is dead.

![image](https://user-images.githubusercontent.com/19180861/76105070-32766680-5f89-11ea-958b-947f8a4cbdae.png)

(but seriously: this is the right decision)
