### ISSUE TITLE
uc_can_io send breaks multi-packet requirement

### ISSUE THREAD

**Issue by mitchpi** [UAVCAN/libuavcan#297]
Hi guys,

I'm looking through the documentation and the code. There is a statement on the this page: https://uavcan.org/Specification/4._CAN_bus_transport_layer/

> All frames of a multi-frame transfer should be pushed to the bus at once, in the proper order from the first frame to the last frame.

However it looks like the current `tx_queues_` in uc_can_io.cpp doesn't support this.
The send method 
```
int CanIOManager::send(const CanFrame &frame, MonotonicTime tx_deadline, MonotonicTime blocking_deadline,
                       uint8_t iface_mask, CanIOFlags flags) 
```
looks at the `tx_queues_` queue to see if the highest priority message in the queue is greater than the new message and tries to send the highest priority item. However the highest priority item in the queue may be the second of 4 parts of a multi part message and may be a lower priority than the new message, hence breaking the above requirement.

The 
```
bool CanTxQueue::topPriorityHigherOrEqual(const CanFrame& rhs_frame)
```
doesn't seem to look at whether the next message in the queue is a multi part message or not.

Is this correct or am I missing a something?

**Comment by pavel-kirienko** [comment]
It is correct, but the problem is not in the implementation but in the specification. In v1.0-alpha it's fixed; instead of the old phrasing, the new spec says this (section 4.1.1.2):

> Implementations should minimize the delay between transmission of transport frames that belong to the same transfer. Transport frames of a multi-frame transfer shall be transmitted following the order of the transfer payload fragments they contain

Further, in 4.1.1.3:

> Transmission of transport frames shall be ordered so that frames of higher priority are transmitted first. It follows that higher-priority transfers may preempt transmission of lower-priority transfers.
