### ISSUE TITLE
Architectural guidance around UAVCAN Gateway

### ISSUE THREAD

**Issue by Janaka-s** [UAVCAN/libuavcan#299]
Hi All,
We are in the process of trying to utilise UAVCAN on a medium size research instrument.  Our scope of work does not allow us to change the Hardware or the System architecture of the instrument.  We want to implement something like the following:
![image](https://user-images.githubusercontent.com/61530120/75411809-9f2fa680-5974-11ea-9b98-db44031f1bc0.png)

Needs and Notes:
* Gateway service needs to forward all CAN packets destined for Service1 and 2, to a MessageBroker over a TCP link.  And carry message from Service1 and 2 back down to embedded Boards over CAN.
* We want to use the DSDL and UAVCAN to encode and decode packets at the MessageBroker
* Service3 and each of the Boards needs to be unique nodes on the CAN network

What is the best way to achieve the Gatewaying using UAVCAN?

**Comment by pavel-kirienko** [comment]
I have moved this discussion to the forum; let us continue there, please: https://forum.uavcan.org/t/architectural-guidance-around-uavcan-gateway/769.

This repository is for issues specific to Libuavcan. It is not the best place for more abstract conversations, especially if they are not related to Libuavcan.
