### ISSUE TITLE
libuavcan_dsdlc missing

### ISSUE THREAD

**Issue by stou-sandalski** [UAVCAN/libuavcan#311]
The instructions on the website https://legacy.uavcan.org/Implementations/Libuavcan/Tutorials/8._Custom_data_types/ refer to libuavcan_dsdlc inside libuavcan but the tool is missing. It doesn't seem to be inside libuavcan, or pyuavcan... 

Where is it? What replaced it? How do you compile "legacy" uavcan dsdls _today_?

**Comment by pavel-kirienko** [comment]
It's on the branch legacy-v0.

**Comment by stou-sandalski** [comment]
Great, thank you. Please update the library readme and the "legacy" website to reflect this because the current situation with the new / legacy APIs and tooling is extremely unclear.
