### ISSUE TITLE
DSDL Identification number

### ISSUE THREAD

**Issue by kmilo7204** [UAVCAN/libuavcan#313]
Hi all,

I will try to explain my issue as good as I can (I hope it helps other people)

Currently I am using legacy-v0 (For Libuavcan and dsdl).

I have an issue related with the DSLD identification numbers (I will explain it better). I am able to use the standard and custom messages (Created with the dsdl_compiler) in different UAVCAN nodes to publish and subscribe to my data.

During my testing phase I found something that I am not able to understand (It is not clear for me) and is regarding my message ID. (Please see the image provided below) 
![UAVCAN_1](https://user-images.githubusercontent.com/49252525/98861956-1ab68280-2434-11eb-809b-e4030913d1ce.png)

From this composed number it is easy for me to understand two things:
XX | Message-ID | Node-ID 

In this case I am publishing a message of type [uavcan/protocol/debug/KeyValue] in the node number 2; however, I do not understand where the first two numbers (18) are defined, it is not clear for me if I can modify that value. 

In addition it also seems weird for me that both of the publishers node starts with 10 instead and both of the published messages in both nodes start with  18  (I attach another image to provide a full view of what I just describe)

![UAVCAN_2](https://user-images.githubusercontent.com/49252525/98862551-19d22080-2435-11eb-8ac7-aa898c33b4d6.png)

Thanks for your help!!

Please let me know if more information is required.

**Comment by pavel-kirienko** [comment]
I think this link will answer your question: https://legacy.uavcan.org/Specification/4._CAN_bus_transport_layer/#can-frame-format (section "ID field")

**Comment by kmilo7204** [comment]
Dear Pavel,

Thank you!!! 

Love this library!!
