### ISSUE TITLE
[QUESTION]: Handling different versions

### ISSUE THREAD

**Issue by kmilo7204** [UAVCAN/libuavcan#314]
Hello Pavel!!

I have a huge question (Actually not sure if this is a proper issue, but I believe is the best place to show it).

Currently in our team we are implementing UAVCAN. As we are running on different platforms we should use two different libraries (libcanard and libuavcan). Everything seems working good when we perform testing inside the libraries (Let's say in the libuavcan side we are able to publish and subscribe successfully and similarly in libcanard) but then there is an issue when we combine both implementations (But there is a reason for it).

On the **libuavcan** side we are using legacy version 0 (As far as we know v1.0 is no ready yet)(It is running on Xavier AGX), on the other hand in the **libcanard** we are using version 1.0 (It is running on a microcontroller). So when we try to publish the heartbeat on the microcontroller we are not able to trigger the subscriber callback on the AGX.

The microcontroller is publishing its node Heartbeat (Matching the specification) and the similarly the AGX, but in the AGX we have a callback to print the received heartbeat, when we look at the data in the CAN bus (candump -caeta can0) we find that Heartbeat sizes are different (8 Bytes for the one in the libcanard and 7 Bytes for the one in libuavcan). 

It is important to say that we are creating the heartbeat message using the dsdl_compiler (Gives a header file for C++), we are using the base provided in the specification but there are some directives missing in the legacy version 0 of this implementation (Please see the code below). We believe that this is the reason of this difference between messages. 

```bash
DsdlCompilerException: bot_dsdl/7509.Heartbeat.uavcan: Internal error: bot_dsdl/7509.Heartbeat.uavcan:37: Invalid attribute name [_offset_]
```

This question might be naive, but I want to ask if there is some problem when using two different versions and two different libraries? (Assuming we are using custom data types). Is there a different way to generate header files for C++, in that way I could use it to generate our hearbeat message (Assuming version 0 of libuavcan can send and receive this message)?. 

I know this question is too long but this is critical for us. I would like to ask you if there is some recommendation you can give us (Should we try in both devices or should we try pyuavcan)?. Your experience and knowledge is so valuable and it would be great to get a hint on this issue.

Thank you!!! 

Please feel free to change the issue name!!

**Comment by pavel-kirienko** [comment]
> This question might be naive, but I want to ask if there is some problem when using two different versions and two different libraries?

Yes, v0 and v1 are not interoperable by design. They can co-exist on the same bus, but they cannot talk to each other. The full list of their differences is in The Guide: https://uavcan.org/guide

> I would like to ask you if there is some recommendation you can give us (Should we try in both devices or should we try pyuavcan)?

Ditch Libuavcan, for now. Stick to PyUAVCAN and Libcanard instead because they are already functional.

Maybe the UAVCAN Forum is a better place for questions of this kind, I think.
