### ISSUE TITLE
Proper file IO loops

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/libuavcan#40]
File read/write should be performed in a loop. See:

* https://github.com/UAVCAN/uavcan/blob/master/libuavcan_drivers/posix/include/uavcan_posix/dynamic_node_id_server/file_event_tracer.hpp#L57
* https://github.com/UAVCAN/uavcan/blob/master/libuavcan_drivers/posix/include/uavcan_posix/dynamic_node_id_server/file_storage_backend.hpp#L84
* https://github.com/UAVCAN/uavcan/blob/master/libuavcan_drivers/posix/include/uavcan_posix/dynamic_node_id_server/file_storage_backend.hpp#L58
* https://github.com/UAVCAN/uavcan/blob/master/libuavcan_drivers/posix/include/uavcan_posix/firmware_version_checker.hpp#L128
* https://github.com/UAVCAN/uavcan/blob/master/libuavcan_drivers/posix/include/uavcan_posix/basic_file_server_backend.hpp#L405

**Comment by davids5** [comment]
@pavel-kirienko see https://github.com/UAVCAN/libuavcan/pull/59 
please test on Linix

**Comment by pavel-kirienko** [comment]
Thanks David! Merged.
