### ISSUE TITLE
Duplicate frames sent CanIface::send

### ISSUE THREAD

**Issue by davids5** [UAVCAN/libuavcan#47]
When bus gets busy we see duplicate frames

![image](https://cloud.githubusercontent.com/assets/1945821/8500499/8005a26a-2138-11e5-9c58-8052716f0242.png)

Here we see all frames are ack-ed and the top trace is CanIface::send

![dupframescaniface_send](https://cloud.githubusercontent.com/assets/1945821/8500464/22f8895c-2138-11e5-9169-29941a26ea8d.png)

**Comment by pavel-kirienko** [comment]
Resolved in the VirtualCanIface class, which is not a part of the library.
