### ISSUE TITLE
Add a tutorial on automatic CAN acceptance filter configuration

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/libuavcan#66]
Here <http://uavcan.org/Implementations/Libuavcan/Tutorials/13._CAN_acceptance_filters>.

**Comment by pavel-kirienko** [comment]
@ilia-sheremet do you feel like writing a tutorial?

**Comment by ilia-sheremet** [comment]
Yes, I will do it!

**Comment by pavel-kirienko** [comment]
http://uavcan.org/Implementations/Libuavcan/Tutorials/13._CAN_acceptance_filters/
