### ISSUE TITLE
Flash and RAM size optimization

### ISSUE THREAD

**Issue by LorenzMeier** [UAVCAN/libuavcan#72]
@pavel-kirienko For a communication library like UAVCAN I would have expected -Os as the default optimisation level - is there a particular reason its -O3? How can I change this to -Os for the PX4 build?

**Comment by pavel-kirienko** [comment]
`-Os` used to break GDB, see https://github.com/UAVCAN/libuavcan/issues/33#issue-81527235. Also, last time we tried `-Os` there was no significant benefit in terms of footprint. @davids5 

In [this branch](https://github.com/UAVCAN/libuavcan/tree/footprint_reduction) I'm currently working on a total refactoring of memory management in libuavcan; I expect it to bring a drastic improvement in both ROM and RAM. There's also one radical and questionable design decision that we're probably going to have to discuss a bit later.

> How can I change this to -Os for the PX4 build?

In `CMakeLists.txt` of the `uavcan` module in PX4, after inclusion of the library:

```cmake
target_compile_options(uavcan PRIVATE -Os)
```

This, however, requires CMake 2.8.12, which is relatively new but comes as default in e.g. Ubuntu 14.04. Another approach is to add a variable containing optimization level that the libuavcan subproject will be picking up.
