### ISSUE TITLE
POSIX storage backend for dynamic node ID allocation server fails to initialize if the directory doesn't exist

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/libuavcan#74]
Discovered with Linux dynamic node ID allocation application: if the storage directory doesn't exist when the application is starting, the backend will create the directory and then fail. On the second attempt it always works fine.

```
Error: libuavcan/libuavcan_drivers/linux/apps/uavcan_dynamic_node_id_server.cpp:495: 0 <= storage_backend.init(persistent_storage_path.c_str())
```

@davids5 FYI.

**Comment by edwinhayes** [comment]
Is this going to be fixed, or is this supposed to be considered normal?

**Comment by pavel-kirienko** [comment]
This is a low priority issue. Somebody should fix it. Please fix it.
