### ISSUE TITLE
Documentation at http://uavcan.org/ outdated 

### ISSUE THREAD

**Issue by ctech4285** [UAVCAN/libuavcan#88]
http://uavcan.org/Implementations/Libuavcan/Platforms/Linux/#uavcan_monitor

needs update

**Comment by pavel-kirienko** [comment]
What exactly does need update?

**Comment by ctech4285** [comment]
Build steps:

cd uavcan  // should be libuavcan
//git submodule update --init missing somewhere 
mkdir build
cd build
cmake ..        # Optionally, set the build type: -DCMAKE_BUILD_TYPE=Release (default is RelWithDebInfo)
make -j4        # This  will invoke the DSDL compiler automatically
sudo make install

**Comment by pavel-kirienko** [comment]
Thanks, fixed. The website should update in a few minutes.
