### ISSUE TITLE
Documentation at http://uavcan.org/ issue

### ISSUE THREAD

**Issue by ctech4285** [UAVCAN/libuavcan#89]
From:
http://uavcan.org/Implementations/Libuavcan/Platforms/Linux/#uavcan_monitor
Section:
uavcan_dynamic_node_id_server
This application implements a dynamic node ID allocation server. Start without arguments to see usage info.

Usage info is crap, this is much better:

uavcan_dynamic_node_id_server 10 can0 -c1 -s .
where:
10 - node ID of the server
can0 - name of the interface
-c1 - cluster size is 1 (no replication, no redundancy)
-s . - keep the persistent state in the current directory
however it's better to make the -s argument absolute, e.g. ~ (your home dir)

**Comment by pavel-kirienko** [comment]
Usage info says exactly that but in a less verbose way.
