### ISSUE TITLE
nuttx uptream only has syslog (lowsyslog is gone)

### ISSUE THREAD

**Issue by davids5** [UAVCAN/libuavcan#95]
When building with https://github.com/UAVCAN/libuavcan/tree/for_upstream_nuttx_changes_4  and chibios this breaks the travise build of UAVCAN/libuavcan (PX4 is fine)

**Comment by pavel-kirienko** [comment]
`lowsyslog()` is part of the Zubax ChibiOS framework, it has no relation to NuttX (other than it's named similarly). In order to fix the failure, `syslog()` should be replaced back with `lowsyslog()` in the demo app.
